const modal=document.getElementById('modal');const box=document.getElementById('modalContent');document.querySelector('.close').onclick=()=>modal.classList.remove('show');modal.onclick=e=>{if(e.target===modal)modal.classList.remove('show')};
const data={
dyslexia:`<h2 class="simTitle">Disleksi Deneyimi</h2><p>Bu metni 15 saniye içinde okumaya çalış:</p><div class="simText shuffle">${[...'Bazen harfler yer değiştiriyormuş gibi hissedilebilir. Okumak daha fazla çaba, zaman ve destek gerektirebilir.'].map(c=>c===' '?' ':`<span>${c}</span>`).join('')}</div><p class="task">Mesaj: Zorluk tembellik değildir; doğru destekle öğrenme güçlenir.</p>`,
adhd:`<h2 class="simTitle">DEHB Deneyimi</h2><p class="task">Aşağıdaki cümleyi okumaya çalışırken uyaranlara dikkat etmemeye çalış.</p><div class="distractions"><div class="pop">Bildirim!</div><div class="pop">Ses!</div><div class="pop">Dikkatini ver!</div><div class="simText">Dikkat dağınıklığı, istememek değil; zihnin aynı anda birçok uyarana çekilmesidir.</div></div>`,
autism:`<h2 class="simTitle">Otizm Spektrum Deneyimi</h2><div class="simText flash">Parlak ışıklar, kalabalık sesler ve ani değişimler bazı bireyler için yoğun ve yorucu olabilir.</div><p class="task">Mesaj: Sakin ortam, açık iletişim ve öngörülebilirlik destekleyicidir.</p>`,
hearing:`<h2 class="simTitle">İşitme Yetersizliği Deneyimi</h2><div class="simText">Düşük sesle söylenen bir bilgiyi kaçırdığını düşün. Şimdi aynı bilgi altyazıyla veriliyor:<br><br><b>“Ders saat 10.30’da başlayacak ve etkinlik salonunda yapılacak.”</b></div><p class="task">Mesaj: Altyazı, yüz yüze iletişim ve net konuşma erişilebilirliği artırır.</p>`,
vision:`<h2 class="simTitle">Görme Yetersizliği Deneyimi</h2><div class="simText blurDemo">Düşük kontrastlı ve bulanık metin okumayı zorlaştırır.</div><div class="accessDemo">Yüksek kontrast ve büyük yazı erişilebilirliği artırır.</div>`
};
document.querySelectorAll('.exp').forEach(b=>b.onclick=()=>{box.innerHTML=data[b.dataset.type];modal.classList.add('show')});
